---
title: "Project Template"
institute: NICD
date: "<div class = 'slide-date'>`r format(Sys.Date(),format='%B %Y')` <div>"
format:
  revealjs:
    slide-number: true
    self-contained: true
---

# Data Science Workflow

## Data Science Workflow Phases

1. Business Understanding
2. Data Preparation and Understanding
3. Modelling
4. Deployment

# Business Understanding

## Steps

1. Information
2. Description
3. Objectives
4. Deliverables
5. Resourcees

## Workflow

# Information

## What?

## Why?

## How?

# Description

## What?

## Why?

## How?

# Objectives

## What?

## Why?

## How?

# Deliverables

## What?

## Why?

## How?

# Resources

## What?

## Why?

## How?

# Data Preparation and Understanding

## Steps

1. Import Data
2. Describe Data
3. Clean Data
4. Explore Data
5. Wrangle Data

## Workflow

## Import Data

### How?

- Create an independent cleaning script in `src/clean` to import data from each relevant data source (directories and / or databases). Each cleaning script should output a file (or a directory of files) in `data/clean/`

### Why?

- A script that can run end-to-end is important for building an automated data pipeline for deployment
- An independent cleaning scipt for each data source is important for script maintenance and reuse

# Describe Data

## What?

## Why?

## How?

# Clean Data

## What?

## Why?

## How?

# Explore Data

## What?

## Why?

## How?

# Wrangle Data

## What?

## Why?

## How?
